###
Get http://localhost:3000/v1/api/test

###
Get http://localhost:3000/v1/api/users

###
Get http://localhost:3000/v1/api/users/1

###
Post http://localhost:3000/v1/api/user
content-type: application/json

{
    "name": "test2",
    "age": 30,
    "email": "test2@test.com"
}


###
Put http://localhost:3000/v1/api/users/1
content-type: application/json

{
    "age": 33
}