###
Get http://localhost:3000/v1/api/test

###
Get http://localhost:3000/v1/api/users

###
Get http://localhost:3000/v1/api/users/7

###
Post http://localhost:3000/v1/api/auth/login
content-type: application/json

{
    "username": "ja",
    "password": "123456"
}

###
Post http://localhost:3000/v1/api/auth/signup
content-type: application/json

{
    "name": "janchow",
    "age": 23,
    "password": "123456",
    "email": "1634889315@qq.com"
}

###
Get http://localhost:3000/v1/api/auth/verify/email/f5364254-0564-40d6-8936-34243f6050a5





###
Post http://localhost:3000/v1/api/user
content-type: application/json

{
    "name": "mike",
    "age": 23,
    "password": "123456",
    "email": "mike@test.com"
}


###
Put http://localhost:3000/v1/api/users/1
content-type: application/json

{
    "age": 30
}

###
Delete http://localhost:3000/v1/api/users/2


###
Get http://localhost:3000/v1/api/products?page=1&size=5&sort=id,desc

###
Get http://localhost:3000/v1/api/products/2


###
Post http://localhost:3000/v1/api/product
content-type: application/json

{
    "name": "蒸排骨",
    "price": 20,
    "description": "好吃排骨"
}